[package]
name = "example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[features]
hot = [ "cargo-hot/enable" ]

[dependencies]
cargo-hot = { path = "..", default-features = false }
crossterm = "0.27.0"
ratatui = "0.26.2"
